FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY core /app/core
COPY db /app/db
COPY bot/utils /app/bot/utils

ENV PYTHONPATH=/app

CMD ["uvicorn", "core.main:app", "--host", "0.0.0.0", "--port", "8000"]
