FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY bot /app/bot
COPY db /app/db

ENV PYTHONPATH=/app

CMD ["python", "-m", "bot.main"]
